[ants]
app = ants.apps.ancil_general_regrid

[ants.sources.sources]
filepath = ${TEST_SOURCES_DIR}/ancil_general_regrid/n96e_orca_land_cover_fraction

[ants.sources.target]
filepath = ${TEST_SOURCES_DIR}/ancil_general_regrid/regular_namelist ${TEST_SOURCES_DIR}/ancil_general_regrid/variable_namelist
target_type = grid

[ants.outputs.netcdf]
saver = netcdf
result = regrid_result
filename = $SCRATCH/app_experiments/grid_to_variable_resolution.nc

[ants.outputs.ancil]
saver = ancil
result = regrid_result
filename = $SCRATCH/app_experiments/grid_to_variable_resolution


[ants.settings]
horizontal_scheme = TwoStage
