[ants]
app = ants.apps.ancil_general_regrid

[ants.sources.sources]
filepath = ${TEST_SOURCES_DIR}/ancil_general_regrid/easy_cdnc_PI-MACv2-SP_v2_two_levels.nc

[ants.sources.target]
filepath = ${TEST_SOURCES_DIR}/ancil_general_regrid/qrparm.mask.nc
target_type = lsm

[ants.settings]
horizontal_scheme = TwoStage

[ants.outputs.output_1]
saver = netcdf
result = regrid_result
filename = $SCRATCH/app_experiments/regrid_result.nc
netcdf_format = NETCDF4

[ants.outputs.output_2]
saver = ancil
result = regrid_result
filename = $SCRATCH/app_experiments/regrid_result
