[command]
default=true

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/CONTRIBUTING.rst]
source=${HOST_SOURCE_ANTS_BASE}/CONTRIBUTING.rst

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/INSTALL.rst]
source=${HOST_SOURCE_ANTS_BASE}/INSTALL.rst

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/README.rst]
source=${HOST_SOURCE_ANTS_BASE}/README.rst

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/bin]
source=${HOST_SOURCE_ANTS_BASE}/lib/ants/cli

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/bin/ants-launch]
source=${HOST_SOURCE_ANTS_BASE}/bin/ants-launch

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/bin/ants-version]
source=${HOST_SOURCE_ANTS_BASE}/bin/ants-version

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/docs]
source=${HOST_SOURCE_ANTS_BASE}/docs

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/lib]
source=${HOST_SOURCE_ANTS_BASE}/lib

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/pyproject.toml]
source=${HOST_SOURCE_ANTS_BASE}/pyproject.toml

[file:$CYLC_WORKFLOW_RUN_DIR/share/fcm_make_ants/build/utils]
source=${HOST_SOURCE_ANTS_BASE}/utils
