name: CI unit tests
on:
    pull_request:
        branches: main
    push:
        branches: main
    workflow_dispatch:

# Limit concurrently running workflow for a specific pull request.
# Cancel and resubmit if a new push is made. See GitHub docs:
# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/control-workflow-concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    pytest:
        name: Run unit tests
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout ANTS
              uses: actions/checkout@v4
              with:
                path: ANTS

            - name: Checkout shumlib
              uses: actions/checkout@v4
              with:
                repository: MetOffice/shumlib
                path: shumlib

            - name: Checkout mule
              uses: actions/checkout@v4
              with:
                repository: MetOffice/mule
                path: mule

            - name: Setup python environment
              uses: mamba-org/setup-micromamba@v2
              with:
                environment-file: ./ANTS/environment.lock
                environment-name: ci-env
                cache-environment: true

            - name: Install shumlib
              working-directory: ./shumlib
              run: |
                echo "Compiling shumlib using $(gfortran --version)"
                make -f ./make/vm-x86-gfortran-gcc.mk check

            - name: Install Mule
              working-directory: ./mule
              run: |
                ./admin/install_mule.sh --spiral_lib --packing_lib \
                                        --shumlib_path $GITHUB_WORKSPACE/shumlib/build/vm-x86-gfortran-gcc \
                                        ./_build/lib ./_build/bin
              shell: micromamba-shell {0}

            - name: Install ANTS
              run: pip install ./ANTS
              shell: micromamba-shell {0}

            - name: Run pytest
              run: |
                set -eu
                PATH=$GITHUB_WORKSPACE/mule/_build/bin:${PATH:-}
                PYTHONPATH=$GITHUB_WORKSPACE/mule/_build/lib:${PYTHONPATH:-}
                pytest --verbose $GITHUB_WORKSPACE/ANTS
              shell: micromamba-shell {0}
